### Show images.
GET {{baseUrl}}/images/json?all=true

### Only images from a final layer (no children) are shown.
GET {{baseUrl}}/images/json?all=false


### Pull or create an image.
POST {{baseUrl}}/images/create?fromImage={{imageName}}&tag={{imageTag}}
Content-Type: application/json

{
}
